src/Entity/Store.php
<?php

namespace App\Entity;

use App\Repository\StoreRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=StoreRepository::class)
 */
class Store
{
    /**
     * @ORM\Id()
     * @ORM\Column(type="uuid", unique=true)
     * @ORM\GeneratedValue(strategy="CUSTOM")
     * @ORM\CustomIdGenerator(class=Ramsey\Uuid\Doctrine\UuidGenerator::class)
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $code;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="text")
     */
    private $address;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_default = false;

    /**
     * @ORM\OneToMany(targetEntity=KmjUser::class, mappedBy="store")
     */
    private $persons;

    /**
     * @ORM\OneToMany(targetEntity=Sale::class, mappedBy="store")
     */
    private $sales;

    public function __construct()
    {
        $this->persons = new ArrayCollection();
        $this->sales = new ArrayCollection();
    }

    public function __toString() 
    {
        return sprintf('%s - %s', $this->getCode(), $this->getName());
    }
    
    public function getId(): ?\Ramsey\Uuid\UuidInterface
    {
        return $this->id;
    }

    public function getCode(): ?string
    {
        return $this->code;
    }

    public function setCode(string $code): self
    {
        $this->code = $code;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getIsDefault(): ?bool
    {
        return $this->is_default;
    }

    public function setIsDefault(bool $is_default = false): self
    {
        $this->is_default = $is_default;

        return $this;
    }

    /**
     * @return Collection|KmjUser[]
     */
    public function getPersons(): Collection
    {
        return $this->persons;
    }

    public function addPerson(KmjUser $person): self
    {
        if (!$this->persons->contains($person)) {
            $this->persons[] = $person;
            $person->setStore($this);
        }

        return $this;
    }

    public function removePerson(KmjUser $person): self
    {
        if ($this->persons->contains($person)) {
            $this->persons->removeElement($person);
            // set the owning side to null (unless already changed)
            if ($person->getStore() === $this) {
                $person->setStore(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Sale[]
     */
    public function getSales(): Collection
    {
        return $this->sales;
    }

    public function addSale(Sale $sale): self
    {
        if (!$this->sales->contains($sale)) {
            $this->sales[] = $sale;
            $sale->setStore($this);
        }

        return $this;
    }

    public function removeSale(Sale $sale): self
    {
        if ($this->sales->contains($sale)) {
            $this->sales->removeElement($sale);
            // set the owning side to null (unless already changed)
            if ($sale->getStore() === $this) {
                $sale->setStore(null);
            }
        }

        return $this;
    }
}

src/Form/StoreType.php
<?php

namespace App\Form;

use App\Entity\Store;
use App\Repository\StoreRepository;
use Symfony\Component\Form\FormError;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Contracts\Translation\TranslatorInterface;

class StoreType extends AbstractType
{
    private $storeRepo, $trans;
    
    public function __construct(StoreRepository $storeRepo, TranslatorInterface $trans) 
    {
        $this->storeRepo = $storeRepo;
        $this->trans = $trans;
    }
    
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('code', null, [
                'label' => 'code'
            ])
            ->add('name', null, [
                'label' => 'name'
            ])
            ->add('address', null, [
                'label' => 'address'
            ])
            ->add('is_default', CheckboxType::class, [
                'label' => 'is_default', 'required' => false
            ])
        ;
        
        $builder->addEventListener(FormEvents::POST_SUBMIT, function(FormEvent $event){
            $data = $event->getData();
            if (!$data->getIsDefault()) {
                
                return;
            }
             
            $defaultStore = $this->storeRepo->findDefaultStore();
            if (!$defaultStore) {
                
                return;
            }
            
            if (!$data->getId()) {
                
                $event->getForm()->addError(new FormError($this->trans->trans('is_default_exist')));
                return;
            }
            
            if ($defaultStore->getId() !== $event->getData()->getId()) {
                $event->getForm()->addError(new FormError($this->trans->trans('is_default_exist')));
            }
        });
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Store::class,
        ]);
    }
}

src/Controller/Admin/StoreController.php
<?php

namespace App\Controller\Admin;

use App\Entity\Store;
use App\Form\StoreType;
use App\Repository\StoreRepository;
use App\Filter\StoreFilterType;
use App\Base\Controller\BaseController;
use App\Library\BreadcrumbBuilder;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

/**
 * @Route("/administrator/store")
 * @author Nur Hidayatullah <kematjaya0@gmail.com>
 */
class StoreController extends BaseController
{
    /**
     * @Route("/", name="store_index", methods={"GET", "POST"})
     */
    public function index(Request $request, BreadcrumbBuilder $builder, StoreRepository $repo):Response
    {
        $builder->getBuilder()->add('administrator');
        $builder->getBuilder()->add('store');
        
        $form = $this->createFormFilter(StoreFilterType::class);
        $queryBuilder = $this->buildFilter($request, $form, $repo->createQueryBuilder('this'));
        
        return $this->render('pages/store/index.html.twig', [
            'title' => 'store', 
            'filter' => $form->createView(),
            'pagination' => parent::createPaginator($queryBuilder, $request)]);
    }
    
    /**
     * @Route("/create", name="store_create", methods={"GET", "POST"})
     */
    public function create(Request $request):Response
    {
        $form = $this->createForm(StoreType::class, new Store(), ["attr" =>["id" => "ajaxForm"], "action" => $this->generateUrl("store_create")]);
        $result = $this->processFormAjax($request, $form);
        if ($result["process"]) {
            
            return $this->json($result);
        }
        
        return $this->render('pages/store/form.html.twig', ['form' => $form->createView(), 'title' => 'create']);
    }
    
    /**
     * @Route("/{id}/edit", name="store_edit", methods={"GET", "POST"})
     */
    public function edit(Store $store, Request $request)
    {
        $form = $this->createForm(StoreType::class, $store, ["attr" =>["id" => "ajaxForm"], "action" => $this->generateUrl("store_edit", ['id' => $store->getId()])]);
        $result = $this->processFormAjax($request, $form);
        if ($result["process"]) {
            
            return $this->json($result);
        }
        
        return $this->render('pages/store/form.html.twig', ['form' => $form->createView(), 'title' => 'edit']);
    }
    
    /**
     * @Route("/{id}/detail", name="store_detail", methods={"GET"})
     */
    public function detail(Store $store)
    {
        return $this->render('pages/store/detail.html.twig', ['data' => $store, 'title' => 'detail']);
    }
    
    /**
     * @Route("/{id}/delete", name="store_delete", methods={"DELETE"})
     */
    public function delete(Store $store, Request $request)
    {
        $tokenName = 'delete'.$store->getId();
        parent::doDelete($request, $store, $tokenName);
        
        return $this->redirectToRoute('store_index');
    }
}

templates/pages/store/_filter.twig
{{form_start(filter)}}
<tr>
    <th>#</th>
    <th>{{ form_widget(filter.code) }}</th>
    <th>{{ form_widget(filter.name) }}</th>
    <th>{{ form_widget(filter.address) }}</th>
    <th>{{ form_widget(filter.is_default) }}</th>
    <th>
        <button type="submit" name="submit" class="btn btn-success btn-sm"><i class="fa fa-search"></i> <span>{{ 'filter'|trans }}</span></button>
        <a href="{{path('store_index', {'_reset' : true })}}" class="btn btn-default btn-sm"><i class="fa fa-recycle"></i> <span>{{ 'reset'|trans }}</span></a>
    </th>
</tr>
{{form_end(filter)}}

templates/pages/store/detail.html.twig
{% extends "modal-layout.html.twig" %}

{% block title %}
    {{ title|trans }}: {{ data.code }}
{% endblock %}


{% block content %}
    <table class="table table-hover table-bordered">
        <tbody>
            <tr>
                <th width="30%">{{ 'code'|trans }}</th>
                <td>{{ data.code }}</td>
            </tr>
            <tr>
                <th>{{ 'name'|trans }}</th>
                <td>{{ data.name }}</td>
            </tr>
            <tr>
                <th>{{ 'address'|trans }}</th>
                <td>{{ data.address }}</td>
            </tr>
            <tr>
                <th>{{ 'is_default'|trans }}</th>
                <td>
                    {{ include('_badge.twig', {is_success: data.isDefault, is_danger: not data.isDefault, label: data.isDefault ? 'yes'|trans : 'no'|trans}) }}
                </td>
            </tr>
        </tbody>
    </table>
{% endblock %}

templates/pages/store/form.html.twig
{% extends "modal-layout.html.twig" %}

{% block title %}
    {{ title|trans }}: {{ 'store'|trans }}
{% endblock %}

{% block actions %}
    <button type="submit" class="btn btn-success"><i class="fa fa-save"></i> {{ 'save'|trans }}</button>
{% endblock %}

{% block form_start %}
    {{ form_start(form) }}
{% endblock %}

{% block form_end %}
    {{ form_end(form) }}
{% endblock %}

{% block content %}
    
    {{ form_widget(form) }}
    
{% endblock %}

templates/pages/store/index.html.twig
{% extends "page-layout.html.twig" %}

{% block title %}
    {{ title|trans }}
{% endblock %}

{% block button_navigation %}
    {{ link_to('store_create', {}, {class: 'btn btn-primary', "data-toggle": 'modal', "data-target": "#myModal"}, '<i class="fa fa-plus"></i> ' ~ 'create'|trans ) }}
{% endblock %}

{% block pagination %}
    {{ knp_pagination_render(pagination) }}
{% endblock %}

{% block page %}
    <table class="table table-hover">
        <thead>
            <tr>
                <th>#</th>
                <th>{{ 'code'|trans }}</th>
                <th>{{ 'name'|trans }}</th>
                <th>{{ 'address'|trans }}</th>
                <th>{{ 'is_default'|trans }}</th>
                <th>{{ 'actions'|trans }}</th>
            </tr>
        </thead>
        <tbody>
            {{ include('pages/store/_filter.twig', {filter: filter}) }}
            {% for k, data in pagination %}
            <tr>
                <th scope="row">{{ (k+1) }}</th>
                <td>{{ data.code }}</td>
                <td>{{ data.name }}</td>
                <td>{{ data.address }}</td>
                <td>{{ include('_badge.twig', {is_success: data.isDefault, is_danger: not data.isDefault, label: data.isDefault ? 'yes'|trans : 'no'|trans}) }}</td>
                <td>
                    <form class="form-inline" method="post" action="{{ path('store_delete', {'id': data.id}) }}" onsubmit="return confirm('{{'confirm.delete'|trans}}');">
                        <input type="hidden" name="_method" value="DELETE">
                        <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ data.id) }}">
                        {{ link_to('store_edit', {id: data.id, object: data, action: ACTION_EDIT}, {class: 'btn btn-xs btn-info', "data-toggle": 'modal', "data-target": "#myModal"}, '<i class="fa fa-edit"></i> ' ~ 'edit'|trans ) }}
                        {{ link_to('store_detail', {id: data.id, object: data, action: ACTION_VIEW}, {class: 'btn btn-xs btn-primary', "data-toggle": 'modal', "data-target": "#myModal"}, '<i class="fa fa-desktop"></i> ' ~ 'detail'|trans ) }}
                        {{ submit_tag('store_delete', {id: data.id, object: data, action: ACTION_DELETE}, {class: 'btn btn-xs btn-danger'}, '<i class="fa fa-trash-o"></i> ' ~ 'delete'|trans ) }}
                    </form>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}