src/Entity/KmjUser.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Kematjaya\UserBundle\Entity\KmjUserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\KmjUserRepository")
 */
class KmjUser implements KmjUserInterface
{
    /**
     * @ORM\Id()
     * @ORM\Column(type="uuid", unique=true)
     * @ORM\GeneratedValue(strategy="CUSTOM")
     * @ORM\CustomIdGenerator(class=Ramsey\Uuid\Doctrine\UuidGenerator::class)
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $username;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_active;

    private $password_old;
    
    private $password_new;
    
    private $password_re_new;

    /**
     * @ORM\ManyToOne(targetEntity=Store::class, inversedBy="persons")
     */
    private $store;

    /**
     * @ORM\OneToMany(targetEntity=KmjPrinterClient::class, mappedBy="kmj_user", orphanRemoval=true)
     */
    private $kmjPrinterClients;

    public function __construct()
    {
        $this->kmjPrinterClients = new ArrayCollection();
    }
    
    const ROLE_OPERATOR = "ROLE_OPERATOR";
    const ROLE_KEPALA = "ROLE_KEPALA";
    
    public function getId(): ?\Ramsey\Uuid\UuidInterface
    {
        return $this->id;
    }

    public function __toString() 
    {
        return $this->getName();
    }
    
    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->username;
    }

    public function setUsername(string $username): KmjUserInterface
    {
        $this->username = $username;

        return $this;
    }

    public function isOperator()
    {
        return in_array(self::ROLE_OPERATOR, $this->getRoles());
    }
    
    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        if(empty($roles))
        {
            $roles[] = self::ROLE_USER;
        }
        

        return array_unique($roles);
    }

    public function setRoles(array $roles): KmjUserInterface
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): KmjUserInterface
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): KmjUserInterface
    {
        $this->name = $name;

        return $this;
    }

    public function getIsActive(): ?bool
    {
        return $this->is_active;
    }

    public function setIsActive(bool $is_active): KmjUserInterface
    {
        $this->is_active = $is_active;

        return $this;
    }
    
    public function setPasswordOld(string $password): KmjUserInterface
    {
        $this->password_old = $password;
        
        return $this;
    }
    
    public function getPasswordOld():?string
    {
        return $this->password_old;
    }
    
    public function setPasswordNew(string $password): KmjUserInterface
    {
        $this->password_new = $password;
        
        return $this;
    }
    
    public function getPasswordNew():?string
    {
        return $this->password_new;
    }
    
    public function setPasswordReNew(string $password): KmjUserInterface
    {
        $this->password_re_new = $password;
        
        return $this;
    }
    
    public function getPasswordReNew():?string
    {
        return $this->password_re_new;
    }

    public function getStore(): ?Store
    {
        return $this->store;
    }

    public function setStore(?Store $store): self
    {
        $this->store = $store;

        return $this;
    }

    /**
     * @return Collection|KmjPrinterClient[]
     */
    public function getKmjPrinterClients(): Collection
    {
        return $this->kmjPrinterClients;
    }

    public function addKmjPrinterClient(KmjPrinterClient $kmjPrinterClient): self
    {
        if (!$this->kmjPrinterClients->contains($kmjPrinterClient)) {
            $this->kmjPrinterClients[] = $kmjPrinterClient;
            $kmjPrinterClient->setKmjUser($this);
        }

        return $this;
    }

    public function removeKmjPrinterClient(KmjPrinterClient $kmjPrinterClient): self
    {
        if ($this->kmjPrinterClients->contains($kmjPrinterClient)) {
            $this->kmjPrinterClients->removeElement($kmjPrinterClient);
            // set the owning side to null (unless already changed)
            if ($kmjPrinterClient->getKmjUser() === $this) {
                $kmjPrinterClient->setKmjUser(null);
            }
        }

        return $this;
    }
}

templates/pages/user/_filter.twig
{{form_start(filter)}}
<tr>
    <th>#</th>
    <th>{{ form_widget(filter.username) }}</th>
    <th>{{ form_widget(filter.name) }}</th>
    <th>{{ form_widget(filter.roles) }}</th>
    <th>{{ form_widget(filter.is_active) }}</th>
    <th>{{ form_widget(filter.store) }}</th>
    <th>
        <button type="submit" name="submit" class="btn btn-success btn-sm"><i class="fa fa-search"></i> <span>{{ 'filter'|trans }}</span></button>
        <a href="{{path('kmj_user_index', {'_reset' : true })}}" class="btn btn-default btn-sm"><i class="fa fa-recycle"></i> <span>{{ 'reset'|trans }}</span></a>
    </th>
</tr>
{{form_end(filter)}}

templates/pages/user/_role.twig
<ul>
    {% for role in roles %}
        <li>{{ role|trans }}</li>
    {% endfor %}
</ul>

templates/pages/user/detail.html.twig
{% extends "modal-layout.html.twig" %}

{% block title %}
    {{ title|trans }}: {{ data.username }}
{% endblock %}


{% block content %}
    <table class="table table-hover table-bordered">
        <tbody>
            <tr>
                <th width="30%">{{ 'username'|trans }}</th>
                <td>{{ data.username }}</td>
            </tr>
            <tr>
                <th>{{ 'name'|trans }}</th>
                <td>{{ data.name }}</td>
            </tr>
            <tr>
                <th>{{ 'roles'|trans }}</th>
                <td>
                    {{ include('pages/user/_role.twig', {roles: data.roles}) }}
                </td>
            </tr>
            <tr>
                <th>{{ 'is_active'|trans }}</th>
                <td>{{ include('_badge.twig', {is_success: data.isActive, is_danger: not data.isActive, label: data.isActive ? 'active'|trans : 'non_active'|trans}) }}</td>
            </tr>
        </tbody>
    </table>
{% endblock %}

templates/pages/user/form.html.twig
{% extends "modal-layout.html.twig" %}

{% block title %}
    {{ title|trans }}: {{ 'user'|trans }}
{% endblock %}

{% block actions %}
    <button type="submit" class="btn btn-success"><i class="fa fa-save"></i> {{ 'save'|trans }}</button>
{% endblock %}

{% block form_start %}
    {{ form_start(form) }}
{% endblock %}

{% block form_end %}
    {{ form_end(form) }}
{% endblock %}

{% block content %}
    
    {{ form_widget(form) }}
    
{% endblock %}

templates/pages/user/index.html.twig
{% extends "page-layout.html.twig" %}

{% block title %}
    {{ title|trans }}
{% endblock %}

{% block button_navigation %}
    {{ link_to('kmj_user_create', {}, {class: 'btn btn-primary', "data-toggle": 'modal', "data-target": "#myModal"}, '<i class="fa fa-plus"></i> ' ~ 'create'|trans ) }}
{% endblock %}

{% block pagination %}
    {{ knp_pagination_render(pagination) }}
{% endblock %}

{% block page %}
    <table class="table table-hover">
        <thead>
            <tr>
                <th>#</th>
                <th>{{ 'username'|trans }}</th>
                <th>{{ 'name'|trans }}</th>
                <th>{{ 'roles'|trans }}</th>
                <th>{{ 'is_active'|trans }}</th>
                <th>{{ 'store'|trans }}</th>
                <th>{{ 'actions'|trans }}</th>
            </tr>
        </thead>
        <tbody>
            {{ include('pages/user/_filter.twig', {filter: filter}) }}
            {% for k, data in pagination %}
            <tr>
                <th scope="row">{{ (k+1) }}</th>
                <td>{{ data.username }}</td>
                <td>{{ data.name }}</td>
                <td>{{ include('pages/user/_role.twig', {roles: data.roles}) }}</td>
                <td>{{ include('_badge.twig', {is_success: data.isActive, is_danger: not data.isActive, label: data.isActive ? 'active'|trans : 'non_active'|trans}) }}</td>
                <td>{{ data.store }}</td>
                <td>
                    <form class="form-inline" method="post" action="{{ path('kmj_user_delete', {'id': data.id}) }}" onsubmit="return confirm('{{'confirm.delete'|trans}}');">
                        <input type="hidden" name="_method" value="DELETE">
                        <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ data.id) }}">
                        
                        {{ link_to('kmj_user_edit', {id: data.id}, {class: 'btn btn-xs btn-info', "data-toggle": 'modal', "data-target": "#myModal"}, '<i class="fa fa-edit"></i> ' ~ 'edit'|trans ) }}
                        {{ link_to('kmj_user_detail', {id: data.id}, {class: 'btn btn-xs btn-primary', "data-toggle": 'modal', "data-target": "#myModal"}, '<i class="fa fa-desktop"></i> ' ~ 'detail'|trans ) }}
                        {{ submit_tag('kmj_user_delete', {id: data.id}, {class: 'btn btn-xs btn-danger'}, '<i class="fa fa-trash-o"></i> ' ~ 'delete'|trans ) }}
                    
                    </form>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}