src/Entity/Sale.php
<?php

namespace App\Entity;

use App\Report\Transaction\TransactionInterface;
use Kematjaya\SaleBundle\Entity\CustomerInterface;
use Kematjaya\SaleBundle\Entity\SaleInterface;
use Kematjaya\CodeManager\Entity\CodeLibraryClientInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\SaleRepository")
 */
class Sale implements SaleInterface, CodeLibraryClientInterface, TransactionInterface
{
    /**
     * @ORM\Id()
     * @ORM\Column(type="uuid", unique=true)
     * @ORM\GeneratedValue(strategy="CUSTOM")
     * @ORM\CustomIdGenerator(class=Ramsey\Uuid\Doctrine\UuidGenerator::class)
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $code;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $created_by;

    /**
     * @ORM\Column(type="float")
     */
    private $sub_total;

    /**
     * @ORM\Column(type="float")
     */
    private $tax;

    /**
     * @ORM\Column(type="float")
     */
    private $total;
    
    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $is_locked;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Customer", inversedBy="sales")
     */
    private $customer;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\SaleItem", mappedBy="sale", orphanRemoval=true)
     */
    private $saleItems;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $discount;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $payment;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $payment_change;

    /**
     * @ORM\ManyToOne(targetEntity=Store::class, inversedBy="sales")
     * @ORM\JoinColumn(nullable=false)
     */
    private $store;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $checked_at;

    public function __construct()
    {
        $this->saleItems = new ArrayCollection();
    }

    public function getId(): ?\Ramsey\Uuid\UuidInterface
    {
        return $this->id;
    }

    public function getCode(): ?string
    {
        return $this->code;
    }

    public function setCode(string $code): SaleInterface
    {
        $this->code = $code;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): SaleInterface
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getCreatedBy(): ?string
    {
        return $this->created_by;
    }

    public function setCreatedBy(string $created_by): SaleInterface
    {
        $this->created_by = $created_by;

        return $this;
    }

    public function getTotal(): ?float
    {
        if(!$this->total and !$this->getSaleItems()->isEmpty())
        {
            foreach($this->getSaleItems() as $saleItem)
            {
                $this->total += $saleItem->getTotal();
            }
            
            $this->total += $this->getTax();
            $this->total -= $this->getDiscount();
        }
        
        return $this->total;
    }

    public function setTotal(float $total): SaleInterface
    {
        $this->total = $total;

        return $this;
    }

    public function getSubTotal(): ?float
    {
        return $this->sub_total;
    }

    public function setSubTotal(float $sub_total): SaleInterface
    {
        $this->sub_total = $sub_total;

        return $this;
    }

    public function getTax(): ?float
    {
        return $this->tax;
    }

    public function setTax(float $tax): SaleInterface
    {
        $this->tax = $tax;

        return $this;
    }

    public function getIsLocked(): ?bool
    {
        return $this->is_locked;
    }

    public function setIsLocked(?bool $is_locked): SaleInterface
    {
        $this->is_locked = $is_locked;

        return $this;
    }

    public function getCustomer(): ?CustomerInterface
    {
        return $this->customer;
    }

    public function setCustomer(?CustomerInterface $customer): SaleInterface
    {
        $this->customer = $customer;

        return $this;
    }

    /**
     * @return Collection|SaleItem[]
     */
    public function getSaleItems(): Collection
    {
        return $this->saleItems;
    }

    public function addSaleItem(SaleItem $saleItem): SaleInterface
    {
        if (!$this->saleItems->contains($saleItem)) {
            $this->saleItems[] = $saleItem;
            $saleItem->setSale($this);
        }

        return $this;
    }

    public function removeSaleItem(SaleItem $saleItem): SaleInterface
    {
        if ($this->saleItems->contains($saleItem)) {
            $this->saleItems->removeElement($saleItem);
            // set the owning side to null (unless already changed)
            if ($saleItem->getSale() === $this) {
                $saleItem->setSale(null);
            }
        }

        return $this;
    }

    public function getDiscount(): ?float
    {
        return $this->discount;
    }

    public function setDiscount(float $discount): SaleInterface
    {
        $this->discount = $discount;

        return $this;
    }

    public function getPayment(): ?float
    {
        return $this->payment;
    }

    public function setPayment(float $payment): SaleInterface
    {
        $this->payment = $payment;

        return $this;
    }

    public function getPaymentChange(): ?float
    {
        if(!$this->payment_change)
        {
            $this->payment_change = $this->getPayment() - $this->getTotal();
        }
        return $this->payment_change;
    }

    public function setPaymentChange(float $payment_change): SaleInterface
    {
        $this->payment_change = $payment_change;

        return $this;
    }

    public function getStore(): ?Store
    {
        return $this->store;
    }

    public function setStore(?Store $store): self
    {
        $this->store = $store;

        return $this;
    }
    
    // =================== CodeManager ===============
    public function getClassId():?string
    {
        return (string) $this->getId();
    }
    
    public function getLibrary():array
    {
        return [
            "type" => 'SL'
        ];
    }
    
    public function getGeneratedCode():?string
    {
        return $this->getCode();
    }
    
    public function setGeneratedCode(string $code): CodeLibraryClientInterface
    {
        return $this->setCode($code);
    }
    
    // =================== end CodeManager ===============

    public function getDescription(): ?string 
    {
        return 'penjualan';
    }

    public function getTypeTransaction(): string 
    {
        return self::TYPE_OUT;
    }

    public function getCredit(): ?float 
    {
        return null;
    }

    public function getDebt(): ?float 
    {
        return $this->getTotal();
    }

    public function isPaid()
    {
        return $this->getPayment() >= $this->getTotal();
    }
    // end implement App\Library\CodeGenerator\Entity\ClientInterface

    public function getCheckedAt(): ?\DateTimeInterface
    {
        return $this->checked_at;
    }

    public function setCheckedAt(?\DateTimeInterface $checked_at): TransactionInterface
    {
        $this->checked_at = $checked_at;

        return $this;
    }
}

src/Controller/Admin/SaleController.php
<?php

namespace App\Controller\Admin;

use App\Entity\Sale;
use App\Form\SaleType;
use App\Filter\SaleFilterType;
use App\Repository\SaleRepository;
use App\Repository\KmjPrinterClientRepository;
use App\Base\Controller\BaseController;
use App\Library\BreadcrumbBuilder;
use Kematjaya\EscposBundle\Helper\PrinterHelperInterface;
use Kematjaya\EscposBundle\Formatter\TextFormatter;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;

/**
 * @Route("/transaction/sale")
 * @author Nur Hidayatullah <kematjaya0@gmail.com>
 */
class SaleController extends BaseController
{
    /**
     * @Route("/", name="sale_index", methods={"GET", "POST"})
     */
    public function index(Request $request, BreadcrumbBuilder $builder, SaleRepository $saleRepo)
    {
        $builder->getBuilder()->add('transaction');
        $builder->getBuilder()->add('sale');
        
        $form = $this->createFormFilter(SaleFilterType::class);
        $queryBuilder = $this->buildFilter($request, $form, $saleRepo->createQueryBuilder('this'));
        return $this->render('pages/sale/index.html.twig', [
            'title' => 'sale', 
            'filter' => $form->createView(),
            'pagination' => parent::createPaginator($queryBuilder, $request)]);
    }
    
    /**
     * @Route("/create", name="sale_create", methods={"GET", "POST"})
     */
    public function create(Request $request, SaleRepository $saleRepo)
    {
        $sale = $saleRepo->createSale();
        $form = $this->createForm(SaleType::class, $sale, ["attr" =>["id" => "ajaxForm"], "action" => $this->generateUrl("sale_create")]);
        $result = $this->processFormAjax($request, $form);
        if ($result["process"]) {
            
            return $this->json($result);
        }
        
        return $this->render('pages/sale/form.html.twig', ['form' => $form->createView(), 'title' => 'create']);
    }
    
    protected function buildSuccessResult(string $type, $object)
    {
        $result = parent::buildSuccessResult($type, $object);
        if ($result["status"]) {
            $result['redirectURL'][] = [
                'url' => $this->generateUrl('sale_detail', ['id' => $object->getId()])
            ];
        }
        
        return $result;
    }
    
    /**
     * @Route("/print-test", name="sale_printout_test", methods={"GET", "POST"})
     */
    public function printTest(Request $request, PrinterHelperInterface $helper, KmjPrinterClientRepository $kmjPrinterClientRepo)
    {
        $printerSelected = null;
        $printers = $kmjPrinterClientRepo->findByUser();
        if (count($printers) > 0) {
            $form = $this->createForm(\App\Form\SelectPrinterType::class);
            $form->handleRequest($request);
            if ($form->isSubmitted()) {
                if ($form->isValid()) {
                    $object = $form->getData();
                    $printerSelected = reset($object);
                }
            }
            
            if (!$printerSelected) {
                return $this->render('pages/select-printer.html.twig', [
                    'form' => $form->createView(), 'backPath' => $this->generateUrl('sale_index')
                ]);
            }
        }else {
            $this->addFlash('error', $this->translator->trans('add_printer'));
            return $this->redirectToRoute('kmj_printer_index');
        }
		
		
        try
        {   
            $formatter = new TextFormatter();
            
            $format = '%-10.40s : %17.40s';
            $formatter
                    ->addText(strtoupper($this->getParameter('app.company')))->addEnter()
                    ->addText("TES PRINT PAGE")->addEnter()->addEnter()
                    ->addText("==============================")->addEnter()
                    ;
                    
            $formatter->setHeader($formatter->getText());
            $formatter->clear();
			
            $helper->print($formatter, $printerSelected);
            dump($this->translator->trans('print_success'));exit;
        }catch (\Exception $ex) {
            dump($ex->getMessage());exit;
        }
		
        dump("OK");exit;
    }
	
        
    /**
     * @Route("/{id}/payment", name="sale_payment", methods={"GET", "POST"})
     */
    public function payment(Sale $sale, Request $request)
    {
        $form = $this->createForm(SaleType::class, $sale, ["attr" =>["id" => "ajaxForm"], "action" => $this->generateUrl("sale_payment", ['id' => $sale->getId()])]);
        
        $result = $this->processFormAjax($request, $form);
        if ($result["process"]) {
            
            return $this->json($result);
        }
        
        return $this->render('pages/sale/payment.html.twig', [
            'form' => $form->createView(), 'title' => 'payment',
            'data' => $sale
        ]);
    }
    
    /**
     * @Route("/{id}/printout", name="sale_printout", methods={"GET", "POST"})
     */
    public function printout(Sale $sale, Request $request, PrinterHelperInterface $helper, KmjPrinterClientRepository $kmjPrinterClientRepo)
    {
        $printerSelected = null;
        $printers = $kmjPrinterClientRepo->findByUser();
        if (count($printers) > 0) {
            $form = $this->createForm(\App\Form\SelectPrinterType::class);
            $form->handleRequest($request);
            if ($form->isSubmitted()) {
                if ($form->isValid()) {
                    $object = $form->getData();
                    $printerSelected = reset($object);
                }
            }
            
            if (!$printerSelected) {
                return $this->render('pages/select-printer.html.twig', [
                    'form' => $form->createView(), 'backPath' => $this->generateUrl('sale_detail', ['id' => $sale->getId()])
                ]);
            }
        }else {
            $this->addFlash('error', $this->translator->trans('add_printer'));
            return $this->redirectToRoute('kmj_printer_index');
        }
            
        try
        {   
            $formatter = new TextFormatter();
            
            $format = '%-10.40s : %17.40s';
            $store = $sale->getStore();
            $formatter
                    ->addText(strtoupper($this->getParameter('app.company')))->addEnter()
                    ->addText($store->getAddress())->addEnter()->addEnter()
                    ->addText("==============================")->addEnter()
                    ;
                    
            $formatter->setHeader($formatter->getText());
            $formatter->clear();
            
            $formatter
                    ->addText(sprintf($format, $this->translator->trans('code'), $sale->getCode()))->addEnter()
                    ->addText(sprintf($format, $this->translator->trans('store'), strtoupper($store->getName())))->addEnter()
                    ->addText(sprintf($format, $this->translator->trans('date'), $sale->getCreatedAt()->format('d/M/Y H:i')))->addEnter()
                    ->addText(sprintf($format, $this->translator->trans('customer'), $sale->getCustomer()))->addEnter()
                    ->addText("==============================")->addEnter();
            
            $subTotal = 0;
            $subTotalDisc = 0;
            $subTotalTax = 0;
            foreach ($sale->getSaleItems() as $saleItem) {
                $line            = sprintf('%-12.40s %1.0f %-1.40s %1.40s : %6.40s', $saleItem->getItem() , $saleItem->getQuantity(), 'x', $saleItem->getSalePrice(), $saleItem->getSubTotal()); 
                $subTotal       += $saleItem->getSubTotal();
                $subTotalDisc   += $saleItem->getDiscount();
                $subTotalTax    += $saleItem->getTax();
                
                $formatter->addText($line)->addEnter();
            }
            
            $discount = $subTotalDisc + $sale->getDiscount();
            $tax = $subTotalTax + $sale->getTax();
            
            $formatter
                    ->addText("==============================")->addEnter()
                    ->addText(sprintf($format, $this->translator->trans('sub_total'), $subTotal))->addEnter()
                    ->addText(sprintf($format, $this->translator->trans('discount'), $discount))->addEnter()
                    ->addText(sprintf($format, $this->translator->trans('tax'), $tax))->addEnter()
                    ->addText(sprintf($format, $this->translator->trans('total'), $sale->getTotal()))->addEnter()
                    ->addText(sprintf($format, $this->translator->trans('payment'), $sale->getPayment()))->addEnter()
                    ->addText(sprintf($format, $this->translator->trans('change'), $sale->getPaymentChange()))->addEnter()
                    ->addText("==============================")->addEnter()
                    ->addText("- Terima Kasih -")->addEnter();
            //dump($formatter->getHeader());
            //dump($formatter->getText());
            //exit;
            $helper->print($formatter, $printerSelected);
            $this->addFlash('info', $this->translator->trans('print_success'));
        }catch (\Exception $ex) 
        {
            $this->addFlash('error', $ex->getMessage());
        } 
        
        
        return $this->redirectToRoute('sale_detail', ['id' => $sale->getId()]);
    }
    
    /**
     * @Route("/{id}/detail", name="sale_detail", methods={"GET", "POST"})
     */
    public function detail(Sale $sale, Request $request, BreadcrumbBuilder $builder)
    {
        $builder->getBuilder()->add('transaction');
        $builder->getBuilder()->add('sale', 'sale_index');
        $builder->getBuilder()->add('detail');
        $builder->getBuilder()->add($sale->getCode());
        
        $form = $this->createForm(SaleType::class, $sale);
        $result = $this->processForm($request, $form);
        if ($result) {
            
            return $this->redirectToRoute('sale_detail', ['id' => $result->getId()]);
        }

templates/pages/sale/_filter.twig
{{form_start(filter)}}
<tr>
    <th>#</th>
    <th>{{ form_widget(filter.store, {attr: {class: "select2-form"}}) }}</th>
    <th>{{ form_widget(filter.code) }}</th>
    <th>
        <div class="col-lg-6">{{ form_widget(filter.created_at.from) }}</div>
        <div class="col-lg-6">{{ form_widget(filter.created_at.to) }}</div>
    </th>
    <th>{{ form_widget(filter.created_by) }}</th>
    <th>{{ form_widget(filter.customer, {attr: {class: "select2-form"}}) }}</th>
    <!--<th>
        <div class="col-lg-6">{# form_widget(filter.sub_total.from) }}</div>
        <div class="col-lg-6">{{ form_widget(filter.sub_total.to) }}</div>
    </th>
    <th>
        <div class="col-lg-6">{{ form_widget(filter.tax.from) }}</div>
        <div class="col-lg-6">{{ form_widget(filter.tax.to) #}</div>
    </th>-->
    <th>
        <div class="col-lg-6">{{ form_widget(filter.total.from) }}</div>
        <div class="col-lg-6">{{ form_widget(filter.total.to) }}</div>
    </th>
    <th>
        <button type="submit" name="submit" class="btn btn-success btn-sm"><i class="fa fa-search"></i> <span>{{ 'filter'|trans }}</span></button>
        <a href="{{path('sale_index', {'_reset' : true })}}" class="btn btn-default btn-sm"><i class="fa fa-recycle"></i> <span>{{ 'reset'|trans }}</span></a>
    </th>
</tr>
{{form_end(filter)}}

templates/pages/sale/_locked.twig
{% if data.getIsLocked() == false %}
    <em class="shortcut-label">(ctrl+c)</em>
    {{ form_widget(form.is_locked) }}
{% endif %}

templates/pages/sale/_sale_item.twig
<table class="table table-hover table-bordered">
    <thead>
        <th width="3%">#</th>
        <th>{{ 'item'|trans }}</th>
        <th style="text-align: right">{{ 'quantity'|trans }}</th>
        <th width="15%" style="text-align: right">{{ 'sale_price'|trans }}</th>
        <th width="15%" style="text-align: right">{{ 'sub_total'|trans }}</th>
        <th width="15%" style="text-align: right">{{ 'tax'|trans }}</th>
        <th width="15%" style="text-align: right">{{ 'total'|trans }}</th>
        <th>{{ 'actions'|trans }}</th>
    </thead>
    <tbody>
        {% set i = 1 %}
        {% set total = 0 %}
        {% for item_sale in data.getSaleItems() %}
            <tr>
                <td>{{ i }}</td>
                <td>{{ item_sale.item }}</td>
                <td style="text-align: right">{{ item_sale.quantity }} {{ (item_sale.item.getSmallestPackages()) ? item_sale.item.getSmallestPackages().packaging.name:'' }}</td>
                <td style="text-align: right">{{ price(item_sale.getSalePrice()) }}</td>
                <td style="text-align: right">{{ price(item_sale.getSubTotal()) }}</td>
                <td style="text-align: right">{{ price(item_sale.getTax()) }}</td>
                <td style="text-align: right">{{ price(item_sale.getTotal()) }}</td>
                <td>
                    {% if data.getIsLocked() == false %}
                        {{ link_to('sale_item_edit', {id: item_sale.id}, {class: 'btn btn-xs btn-info', "data-toggle": 'modal', "data-target": "#myModal"}, '<i class="fa fa-edit"></i> ' ~ 'edit'|trans ) }}
                        {{ link_to('sale_item_delete', {id: item_sale.id}, {class: 'btn btn-xs btn-danger btn-delete', "_token": csrf_token('delete' ~ item_sale.id), onclick: "return confirm('"~ 'confirm.delete'|trans ~"');"}, '<i class="fa fa-trash-o"></i> ' ~ 'delete'|trans ) }}
                    {% endif %}
                </td>
            </tr>
            {% set total = total + item_sale.getTotal() %}
            {% set i = i + 1 %}
        {% endfor %}
    </tbody>
    
    <tfoot>
        <tr>
            <th colspan="4">{{ 'tax'|trans }} <em class="shortcut-label">(ctrl+x)</em></th>
            <th>{{ form_widget(form.tax, {attr: {onchange: 'return countTotal()'}}) }}</th>
            <th>{{ 'sub_total'|trans }}</th>
            <th width="10%">{{ form_widget(form.sub_total, {value: total, attr:{readonly: true}}) }}</th>
            <th></th>
        </tr>
        <tr>
            <th colspan="4">{{ 'discount'|trans }} <em class="shortcut-label">(ctrl+d)</em></th>
            <th>{{ form_widget(form.discount, {attr: {onchange: 'return countTotal()'}}) }}</th>
            <th>{{ 'total'|trans }}</th>
            <th>{{ form_widget(form.total, {attr:{readonly: true}}) }}</th>
            <th></th>
        </tr>
        <tr>
            <th colspan="4">{{ 'payment'|trans }} <em class="shortcut-label">(ctrl+p)</em></th>
            <th>{{ form_widget(form.payment, {attr: {onchange: 'return countPaymentChange()'}}) }}</th>
            <th>{{ 'payment_change'|trans }}</th>
            <th>{{ form_widget(form.payment_change, {attr:{readonly: true}}) }}</th>
            <th></th>
        </tr>
        <tr>
            <th colspan="8">
                {{ include('pages/sale/_locked.twig', {form: form, data: data}) }}
            </th>
        </tr>
    </tfoot>
    
</table>

templates/pages/sale/detail.html.twig
{% extends "page-layout.html.twig" %}

{% block title %}
    {{ title|trans }} {{ 'sale'|trans }}: {{ data.code }}
{% endblock %}

{% block button_navigation %}
    <a href="{{ path('sale_index') }}" class="btn btn-primary"><i class="fa fa-list"></i> {{ 'back'|trans }}</a>
{% endblock %}

{% block page %}
    {{ form_start(form) }}
    <table class="table table-hover table-bordered">
        <tbody>
            <tr>
                <th width="30%">{{ 'code'|trans }}</th>
                <td>{{ form_widget(form.code) }}</td>
            </tr>
            <tr>
                <th>{{ 'customer'|trans }}</th>
                <td>{{ form_widget(form.customer, {attr: {class: "select2-form"}}) }}</td>
            </tr>
            <tr>
                <th>{{ 'store'|trans }}</th>
                <td>{{ form_widget(form.store, {attr: {class: "select2-form"}}) }}</td>
            </tr>
            {% if data.getIsLocked() %}
                <tr>
                    <th>{{ 'is_locked'|trans }}</th>
                    <td>
                        {{ include('@SimpleAdmin/_boolean_field.twig', {is_check: data.getIsLocked}) }}
                    </td>
                </tr>
            {% endif %}
        </tbody>
    </table>
    
    
    <div class="pull-right">
        
    {% if data.getIsLocked() == false %}
        <button type="submit" class="btn btn-success" id="btnSave"><i class="fa fa-save"></i> {{ 'save'|trans }} <em class="shortcut-label">(ctrl+s)</em></button>
        {{ link_to('sale_item_create', {id: data.id}, {class: 'btn btn-primary', "id": "btnAdd", "data-toggle": 'modal', "data-target": "#myModal"}, '<i class="fa fa-plus"></i> ' ~ 'add_item'|trans ~ ' <em class="shortcut-label">(ctrl+a)</em>' ) }}
    
    {% else %}
        {{ link_to('sale_printout', {id: data.id, object: data, action: 'print'}, {class: 'btn btn-primary', "id": "btnPrint"}, '<i class="fa fa-print"></i> ' ~ 'print'|trans ~ ' <em class="shortcut-label">(ctrl+p)</em>') }}
        {{ link_to('sale_payment', {id: data.id, object: data, action: 'pay'}, {class: 'btn btn-success', "data-toggle": 'modal', "data-target": "#myModal"}, '<i class="fa fa-money"></i> ' ~ 'payment'|trans ) }}
    {% endif %}
    </div>
    
    {{ include('pages/sale/_sale_item.twig', {data: data, form: form}) }}
    
    
    {{ form_end(form) }}
{% endblock %}
{% block javascripts %}
    {{ parent() }}
<script src="{{ asset('assets/js/hotkeys.min.js')}}"></script>
<script>
    
    hotkeys('ctrl+a,ctrl+s,ctrl+x,ctrl+d, ctrl+p, ctrl+c', function (event, handler){
        
        event.preventDefault();
        switch (handler.key) {
            case 'ctrl+a':
                $("#btnAdd").click();
                break;
            case 'ctrl+s':
                $("#btnSave").click();
                break;
            case 'ctrl+x':
                $('#sale_tax').focus();
                break;
            case 'ctrl+d':
                $('#sale_discount').focus();
                break;
            case 'ctrl+p':
                {% if data.getIsLocked() %}
                    window.location.href = "{{path('sale_printout', {id: data.id})}}";
                {% else %}
                    $('#sale_payment').focus();
                {% endif %}
                break;
            case 'ctrl+c':
                $('#sale_is_locked').prop('checked', !$('#sale_is_locked').is(':checked'));
                $.uniform.update();
                break;
            default: alert(event);
        }
    });
    
    $(function(){
        $('.btn-delete').each(function (){
            let token = $(this).attr('_token');
            $(this).on("click",function(e) {
            e.preventDefault();
            $.ajax({
                url: this.href,
                type: 'POST',
                data: {_token: token, _method: 'DELETE'},
                success: function (e){
                    if(e.status)
                    {
                        location.reload();
                    }else
                    {
                        alert(e.message);
                    }
                }, 
                error: function () {
                    alert('error');
                }
            });
          });
        });
    });
    
    function getTax()
    {
        return parseFloat($("#sale_tax").unmask());
    }
    function getDiscount()
    {
        return parseFloat($("#sale_discount").unmask());
    }
    function getPayment()
    {
        return parseFloat($("#sale_payment").unmask());
    }
    function getSubTotal()
    {
        return parseFloat($("#sale_sub_total").unmask());
    }
    function getTotal()
    {
        return parseFloat($("#sale_total").unmask());
    }
    
    function countTotal()
    {
        let total = (getSubTotal() + getTax()) - getDiscount();
        $("#sale_total").val(total);
        countPaymentChange();
    }
    function countPaymentChange()
    {
        let change = getPayment() - getTotal();
        $("#sale_payment_change").val(change);
        refreshPriceformat();
    }
</script>
{% endblock %}
    

templates/pages/sale/index.html.twig
{% extends "page-layout.html.twig" %}

{% block title %}
    {{ title|trans }}
{% endblock %}

{% block button_navigation %}
    {{ link_to('sale_create', {}, {class: 'btn btn-primary', "data-toggle": 'modal', "data-target": "#myModal"}, '<i class="fa fa-plus"></i> ' ~ 'create'|trans ) }}
{% endblock %}

{% block pagination %}
    {{ knp_pagination_render(pagination) }}
{% endblock %}

{% block page %}
    <table class="table table-hover">
        <thead>
            <tr>
                <th>#</th>
                <th>{{ 'store'|trans }}</th>
                <th>{{ 'code'|trans }}</th>
                <th>{{ 'created_at'|trans }}</th>
                <th>{{ 'created_by'|trans }}</th>
                <th>{{ 'customer'|trans }}</th>
                <th>{{ 'total'|trans }}</th>
                <th>{{ 'actions'|trans }}</th>
            </tr>
        </thead>
        <tbody>
            {{ include('pages/sale/_filter.twig', {filter: filter}) }}
            {% for k, data in pagination %}
            <tr>
                <th scope="row">{{ (k+1) }}</th>
                <td>{{ data.store }}</td>
                <td>{{ data.code }}</td>
                <td>{{ data.createdAt|date('d M Y :H:i') }}</td>
                <td>{{ data.createdBy }}</td>
                <td>{{ data.customer }}</td>
                <td style="text-align: right">{{ price(data.total) }}</td>
                <td>
                    <form class="form-inline" method="post" action="{{ path('sale_delete', {'id': data.id}) }}" onsubmit="return confirm('{{'confirm.delete'|trans}}');">
                        <input type="hidden" name="_method" value="DELETE">
                        <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ data.id) }}">
                        {{ submit_tag('sale_delete', {id: data.id, object: data, action: ACTION_DELETE}, {class: 'btn btn-xs btn-danger'}, '<i class="fa fa-trash-o"></i> ' ~ 'delete'|trans ) }}
                    </form>
                    {{ link_to('sale_detail', {id: data.id, object: data, action: ACTION_VIEW}, {class: 'btn btn-xs btn-primary'}, '<i class="fa fa-desktop"></i> ' ~ 'detail'|trans ) }}
                    {{ link_to('sale_payment', {id: data.id, object: data, action: 'pay'}, {class: 'btn btn-xs btn-success', "data-toggle": 'modal', "data-target": "#myModal"}, '<i class="fa fa-money"></i> ' ~ 'payment'|trans ) }}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}